require 'douban2/client'
require 'douban2/config'
require 'douban2/strategy/auth_code.rb'
require 'douban2/interface/base'
require 'douban2/interface/friends'
require 'douban2/interface/share'
require 'douban2/interface/status'
require 'douban2/interface/users'
